export const TOTAL_SALE_REQUEST = "TOTAL_SALE_REQUEST";
export const TOTAL_SALE_SUCCESS = "TOTAL_SALE_SUCCESS";
export const TOTAL_SALE_FAIL = "TOTAL_SALE_FAIL";

export const TOTAL_PRODUCTS_REQUEST = "TOTAL_PRODUCTS_REQUEST";
export const TOTAL_PRODUCTS_SUCCESS = "TOTAL_PRODUCTS_SUCCESS";
export const TOTAL_PRODUCTS_FAIL = "TOTAL_PRODUCTS_FAIL";

export const TOTAL_USERS_REQUEST = "TOTAL_USERS_REQUEST";
export const TOTAL_USERS_SUCCESS = "TOTAL_USERS_SUCCESS";
export const TOTAL_USERS_FAIL = "TOTAL_USERS_FAIL";

export const TOTAL_ORDERS_REQUEST = "TOTAL_ORDERS_REQUEST";
export const TOTAL_ORDERS_SUCCESS = "TOTAL_ORDERS_SUCCESS";
export const TOTAL_ORDERS_FAIL = "TOTAL_ORDERS_FAIL";

export const DASHBOARD_SALES_GRAPH_REQUEST = "DASHBOARD_SALES_GRAPH_REQUEST";
export const DASHBOARD_SALES_GRAPH_SUCCESS = "DASHBOARD_SALES_GRAPH_SUCCESS";
export const DASHBOARD_SALES_GRAPH_FAIL = "DASHBOARD_SALES_GRAPH_FAIL";
