export const USER_FEEDBACK_REQUEST = "USER_FEEDBACK_REQUEST";
export const USER_FEEDBACK_SUCCESS = "USER_FEEDBACK_SUCCESS";
export const USER_FEEDBACK_FAIL = "USER_FEEDBACK_FAIL";

export const ADMIN_FEEDBACK_REQUEST = "ADMIN_FEEDBACK_REQUEST";
export const ADMIN_FEEDBACK_SUCCESS = "ADMIN_FEEDBACK_SUCCESS";
export const ADMIN_FEEDBACK_FAIL = "ADMIN_FEEDBACK_FAIL";
